# -*- coding: utf-8 -*-
"""Copy of VSR_baseline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OV_KRrtcejbiypRYCMBhIR1WCuMpLdPI

# Video Super-Resolution Baseline

Goal:
Build a first working baseline for Video Super-Resolution (VSR):
- Load video frame sequences
- Generate synthetic low-resolution inputs from high-resolution frames
- Train a baseline model
- Verify the end-to-end pipeline works
"""

import os
import cv2
import math
import time
import random
import urllib.request
import numpy as np
import matplotlib.pyplot as plt

from pathlib import Path
from collections import defaultdict

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

from torch.utils.data import Dataset, DataLoader
from google.colab import drive

drive.mount('/content/drive')

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
PIN_MEMORY = torch.cuda.is_available()

print("Device:", device)
print("CUDA available:", torch.cuda.is_available())

LOCAL_DATA = Path("/content/MyVSR")
RAW_VIDEO_DIR = LOCAL_DATA / "raw_videos"
SPLIT_ROOT = LOCAL_DATA / "splits"
SAVE_DIR = LOCAL_DATA / "checkpoints"
RESULTS_DIR = LOCAL_DATA / "results"

for p in [RAW_VIDEO_DIR, SPLIT_ROOT, SAVE_DIR, RESULTS_DIR]:
    p.mkdir(parents=True, exist_ok=True)

# Baseline config
SEQ_LEN = 5
SCALE = 4
PATCH_SIZE = 64
BATCH_SIZE = 4
NUM_EPOCHS = 30
LR = 2e-4

# Extraction config
FRAMES_PER_CLIP = 160

# Reproducibility
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

print("Setup done.")

video_sources = {
    "tears": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    "bunny": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "sintel": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
    "dream": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
}

for name, url in video_sources.items():
    out_path = RAW_VIDEO_DIR / f"{name}.mp4"
    if not out_path.exists():
        print(f"Downloading {name}...")
        urllib.request.urlretrieve(url, out_path)
    else:
        print(f"Exists: {out_path}")

print("All videos ready.")

# חשוב: כל source video שייך רק ל-split אחד
split_plan = [
    # TRAIN
    ("train", "tears",  "clip1",  60000),
    ("train", "tears",  "clip2", 180000),
    ("train", "tears",  "clip3", 300000),

    ("train", "bunny",  "clip1",  30000),
    ("train", "bunny",  "clip2", 120000),

    # VAL
    ("val",   "dream",  "clip1",  20000),
    ("val",   "dream",  "clip2", 120000),

    # TEST
    ("test",  "sintel", "clip1",  20000),
    ("test",  "sintel", "clip2", 120000),
]

def make_clip_name(video_key, clip_name):
    return f"{video_key}_{clip_name}"

for split, video_key, clip_name, _ in split_plan:
    clip_dir = SPLIT_ROOT / split / make_clip_name(video_key, clip_name)
    (clip_dir / "hr_frames").mkdir(parents=True, exist_ok=True)
    (clip_dir / "lr_frames").mkdir(parents=True, exist_ok=True)

print("Split directories created.")

DELETE_OLD_FRAMES = True

if DELETE_OLD_FRAMES:
    deleted = 0
    for p in SPLIT_ROOT.rglob("*.png"):
        p.unlink()
        deleted += 1
    print(f"Deleted {deleted} old frame files.")
else:
    print("Skipping frame cleanup.")

def extract_segment(video_path, start_ms, split_name, clip_name, num_frames=160, scale=4):
    cap = cv2.VideoCapture(str(video_path))
    cap.set(cv2.CAP_PROP_POS_MSEC, start_ms)

    hr_dir = SPLIT_ROOT / split_name / clip_name / "hr_frames"
    lr_dir = SPLIT_ROOT / split_name / clip_name / "lr_frames"

    count = 0
    while count < num_frames:
        ret, frame = cap.read()
        if not ret:
            break

        hr_file = hr_dir / f"{count:04d}.png"
        lr_file = lr_dir / f"{count:04d}.png"

        cv2.imwrite(str(hr_file), frame)

        lr_frame = cv2.resize(
            frame,
            (frame.shape[1] // scale, frame.shape[0] // scale),
            interpolation=cv2.INTER_CUBIC
        )
        cv2.imwrite(str(lr_file), lr_frame)

        count += 1

    cap.release()
    print(f"Finished {split_name}/{clip_name} from {video_path.name} with {count} frames")

for split_name, video_key, short_clip_name, start_ms in split_plan:
    clip_name = make_clip_name(video_key, short_clip_name)
    extract_segment(
        RAW_VIDEO_DIR / f"{video_key}.mp4",
        start_ms,
        split_name,
        clip_name,
        num_frames=FRAMES_PER_CLIP,
        scale=SCALE
    )

for split in ["train", "val", "test"]:
    hr_count = len(list((SPLIT_ROOT / split).rglob("hr_frames/*.png")))
    lr_count = len(list((SPLIT_ROOT / split).rglob("lr_frames/*.png")))
    print(split, "hr:", hr_count, "lr:", lr_count)

def img_to_tensor(img):
    img = img.astype(np.float32) / 255.0
    img = np.transpose(img, (2, 0, 1))
    return torch.from_numpy(img)

def tensor_to_img(tensor):
    img = tensor.detach().cpu().clamp(0, 1).numpy()
    img = np.transpose(img, (1, 2, 0))
    img = (img * 255.0).round().astype(np.uint8)
    return img

def add_light_degradation(img):
    out = img.copy()

    if random.random() < 0.3:
        out = cv2.GaussianBlur(out, (3, 3), 0)

    if random.random() < 0.3:
        noise = np.random.normal(0, 2.0, out.shape).astype(np.float32)
        out = np.clip(out.astype(np.float32) + noise, 0, 255).astype(np.uint8)

    return out

def psnr_torch(pred, target, max_val=1.0):
    h = min(pred.shape[-2], target.shape[-2])
    w = min(pred.shape[-1], target.shape[-1])

    pred = pred[..., :h, :w]
    target = target[..., :h, :w]

    mse = F.mse_loss(pred, target)
    if mse.item() == 0:
        return 99.0
    return 20 * math.log10(max_val) - 10 * math.log10(mse.item())

class CustomVideoDataset(Dataset):
    def __init__(
        self,
        split_root,
        split="train",
        seq_len=5,
        scale=4,
        patch_size=64,
        return_full_frame=False
    ):
        self.split_root = Path(split_root)
        self.split = split
        self.seq_len = seq_len
        self.scale = scale
        self.patch_size = patch_size
        self.return_full_frame = return_full_frame
        self.use_augmentation = (split == "train")
        self.samples = []

        split_dir = self.split_root / split
        clip_dirs = sorted([p for p in split_dir.iterdir() if p.is_dir()])

        for clip_dir in clip_dirs:
            hr_frames = sorted((clip_dir / "hr_frames").glob("*.png"))
            lr_frames = sorted((clip_dir / "lr_frames").glob("*.png"))

            if len(hr_frames) != len(lr_frames):
                print(f"Skipping {clip_dir.name}: HR/LR mismatch")
                continue

            if len(hr_frames) < seq_len:
                print(f"Skipping {clip_dir.name}: too short")
                continue

            for i in range(len(hr_frames) - seq_len + 1):
                self.samples.append({
                    "clip_name": clip_dir.name,
                    "hr": hr_frames[i:i + seq_len],
                    "lr": lr_frames[i:i + seq_len],
                    "start_idx": i
                })

        print(f"{split}: loaded {len(self.samples)} samples")

    def __len__(self):
        return len(self.samples)

    def _read_img(self, path):
        img = cv2.imread(str(path))
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        return img

    def _deterministic_crop(self, h, w, lp, idx):
        # קבוע ל-val/test
        top = max((h - lp) // 2, 0)
        left = max((w - lp) // 2, 0)
        return top, left

    def __getitem__(self, idx):
        sample = self.samples[idx]
        hr_frames = [self._read_img(p) for p in sample["hr"]]
        lr_frames = [self._read_img(p) for p in sample["lr"]]

        if self.return_full_frame:
            lr_tensors = torch.stack([img_to_tensor(img) for img in lr_frames], dim=0)
            hr_tensors = torch.stack([img_to_tensor(img) for img in hr_frames], dim=0)
            return lr_tensors, hr_tensors, sample["clip_name"], sample["start_idx"]

        lp = self.patch_size
        hp = lp * self.scale
        h, w = lr_frames[0].shape[:2]

        if h < lp or w < lp:
            raise ValueError(f"Patch size {lp} too large for LR frame size {(h, w)}")

        if self.split == "train":
            top = random.randint(0, h - lp)
            left = random.randint(0, w - lp)
        else:
            top, left = self._deterministic_crop(h, w, lp, idx)

        lr_patches = [f[top:top + lp, left:left + lp] for f in lr_frames]
        hr_patches = [
            f[top * self.scale: top * self.scale + hp,
              left * self.scale: left * self.scale + hp]
            for f in hr_frames
        ]

        if self.use_augmentation:
            if random.random() < 0.5:
                lr_patches = [np.fliplr(img).copy() for img in lr_patches]
                hr_patches = [np.fliplr(img).copy() for img in hr_patches]

            if random.random() < 0.5:
                lr_patches = [np.flipud(img).copy() for img in lr_patches]
                hr_patches = [np.flipud(img).copy() for img in hr_patches]

            if random.random() < 0.3:
                lr_patches = [add_light_degradation(img) for img in lr_patches]

        lr_tensors = torch.stack([img_to_tensor(img) for img in lr_patches], dim=0)
        hr_tensors = torch.stack([img_to_tensor(img) for img in hr_patches], dim=0)

        return lr_tensors, hr_tensors

train_dataset = CustomVideoDataset(
    SPLIT_ROOT, split="train", seq_len=SEQ_LEN, scale=SCALE, patch_size=PATCH_SIZE
)

val_dataset = CustomVideoDataset(
    SPLIT_ROOT, split="val", seq_len=SEQ_LEN, scale=SCALE, patch_size=PATCH_SIZE
)

test_dataset = CustomVideoDataset(
    SPLIT_ROOT, split="test", seq_len=SEQ_LEN, scale=SCALE, patch_size=PATCH_SIZE
)

# להערכת full-frame
val_full_dataset = CustomVideoDataset(
    SPLIT_ROOT, split="val", seq_len=SEQ_LEN, scale=SCALE, patch_size=PATCH_SIZE, return_full_frame=True
)

test_full_dataset = CustomVideoDataset(
    SPLIT_ROOT, split="test", seq_len=SEQ_LEN, scale=SCALE, patch_size=PATCH_SIZE, return_full_frame=True
)

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=0,
    pin_memory=PIN_MEMORY
)

val_loader = DataLoader(
    val_dataset,
    batch_size=1,
    shuffle=False,
    num_workers=0,
    pin_memory=PIN_MEMORY
)

test_loader = DataLoader(
    test_dataset,
    batch_size=1,
    shuffle=False,
    num_workers=0,
    pin_memory=PIN_MEMORY
)

val_full_loader = DataLoader(
    val_full_dataset,
    batch_size=1,
    shuffle=False,
    num_workers=0,
    pin_memory=PIN_MEMORY
)

test_full_loader = DataLoader(
    test_full_dataset,
    batch_size=1,
    shuffle=False,
    num_workers=0,
    pin_memory=PIN_MEMORY
)

print("train samples:", len(train_dataset))
print("val samples:", len(val_dataset))
print("test samples:", len(test_dataset))
print("val full samples:", len(val_full_dataset))
print("test full samples:", len(test_full_dataset))

lr_batch, hr_batch = next(iter(train_loader))
print("LR batch shape:", lr_batch.shape)  # [B, T, C, H, W]
print("HR batch shape:", hr_batch.shape)  # [B, T, C, H*scale, W*scale]

assert lr_batch.ndim == 5
assert hr_batch.ndim == 5
assert lr_batch.shape[1] == SEQ_LEN
assert hr_batch.shape[1] == SEQ_LEN

print("Sanity check passed.")

class ResidualBlock(nn.Module):
    def __init__(self, num_feat):
        super().__init__()
        self.conv1 = nn.Conv2d(num_feat, num_feat, 3, 1, 1)
        self.relu = nn.ReLU(inplace=True)
        self.conv2 = nn.Conv2d(num_feat, num_feat, 3, 1, 1)

    def forward(self, x):
        identity = x
        out = self.relu(self.conv1(x))
        out = self.conv2(out)
        return identity + out


class ResidualVSRModel(nn.Module):
    def __init__(self, seq_len=5, in_channels=3, num_feat=64, num_blocks=10, scale=4):
        super().__init__()
        self.seq_len = seq_len
        self.scale = scale

        self.conv_first = nn.Conv2d(seq_len * in_channels, num_feat, 3, 1, 1)
        self.body = nn.Sequential(*[ResidualBlock(num_feat) for _ in range(num_blocks)])

        self.upsample = nn.Sequential(
            nn.Conv2d(num_feat, num_feat * (scale ** 2), 3, 1, 1),
            nn.PixelShuffle(scale),
            nn.Conv2d(num_feat, 3, 3, 1, 1)
        )

    def forward(self, x):
        # x: [B, T, C, H, W]
        b, t, c, h, w = x.shape
        x = x.view(b, t * c, h, w)
        feat = self.conv_first(x)
        feat = self.body(feat)
        out = self.upsample(feat)
        return out


model = ResidualVSRModel(seq_len=SEQ_LEN, scale=SCALE).to(device)
num_params = sum(p.numel() for p in model.parameters())
print(f"Model parameters: {num_params:,}")

criterion = nn.L1Loss()
optimizer = optim.Adam(model.parameters(), lr=LR)
scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=5, gamma=0.5)

BEST_PATH = SAVE_DIR / "vsr_model_best.pth"
LAST_PATH = SAVE_DIR / "vsr_model_last.pth"

print("Optimizer and scheduler ready.")

def train_one_epoch(model, loader, optimizer, criterion, device):
    model.train()
    running_loss = 0.0

    for lr_seq, hr_seq in loader:
        lr_seq = lr_seq.to(device, non_blocking=True)
        hr_seq = hr_seq.to(device, non_blocking=True)

        target = hr_seq[:, hr_seq.shape[1] // 2]

        optimizer.zero_grad(set_to_none=True)
        pred = model(lr_seq)
        loss = criterion(pred, target)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

    return running_loss / max(len(loader), 1)


@torch.no_grad()
def evaluate_patch_loader(model, loader, criterion, device):
    model.eval()
    running_loss = 0.0
    running_psnr = 0.0

    for lr_seq, hr_seq in loader:
        lr_seq = lr_seq.to(device, non_blocking=True)
        hr_seq = hr_seq.to(device, non_blocking=True)

        target = hr_seq[:, hr_seq.shape[1] // 2]
        pred = model(lr_seq)

        loss = criterion(pred, target)
        psnr = psnr_torch(pred, target)

        running_loss += loss.item()
        running_psnr += psnr

    avg_loss = running_loss / max(len(loader), 1)
    avg_psnr = running_psnr / max(len(loader), 1)
    return avg_loss, avg_psnr


@torch.no_grad()
def evaluate_full_frame_loader(model, loader, device):
    model.eval()
    psnrs = []

    for lr_seq, hr_seq, clip_name, start_idx in loader:
        lr_seq = lr_seq.to(device, non_blocking=True)   # [1, T, C, H, W]
        hr_seq = hr_seq.to(device, non_blocking=True)

        target = hr_seq[:, hr_seq.shape[1] // 2]
        pred = model(lr_seq)

        psnrs.append(psnr_torch(pred, target))

    return float(np.mean(psnrs)) if len(psnrs) > 0 else 0.0

history = {
    "train_loss": [],
    "val_loss": [],
    "val_psnr_patch": []
}

best_val_psnr = -1.0

for epoch in range(1, NUM_EPOCHS + 1):
    t0 = time.time()

    train_loss = train_one_epoch(model, train_loader, optimizer, criterion, device)
    val_loss, val_psnr_patch = evaluate_patch_loader(model, val_loader, criterion, device)

    scheduler.step()

    history["train_loss"].append(train_loss)
    history["val_loss"].append(val_loss)
    history["val_psnr_patch"].append(val_psnr_patch)

    torch.save(model.state_dict(), LAST_PATH)

    if val_psnr_patch > best_val_psnr:
        best_val_psnr = val_psnr_patch
        torch.save(model.state_dict(), BEST_PATH)
        best_mark = " <-- best"
    else:
        best_mark = ""

    dt = time.time() - t0
    print(
        f"Epoch [{epoch}/{NUM_EPOCHS}] "
        f"train_loss={train_loss:.4f} "
        f"val_loss={val_loss:.4f} "
        f"val_psnr_patch={val_psnr_patch:.2f} "
        f"time={dt:.1f}s"
        f"{best_mark}"
    )

print("Training done.")

plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(history["train_loss"], label="train_loss")
plt.plot(history["val_loss"], label="val_loss")
plt.title("Loss")
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history["val_psnr_patch"], label="val_psnr_patch")
plt.title("Val PSNR (patch)")
plt.legend()

plt.tight_layout()
plt.show()

model.load_state_dict(torch.load(BEST_PATH, map_location=device))
model.eval()

test_loss, test_psnr_patch = evaluate_patch_loader(model, test_loader, criterion, device)
test_psnr_full = evaluate_full_frame_loader(model, test_full_loader, device)

print(f"Test patch loss: {test_loss:.4f}")
print(f"Test patch PSNR: {test_psnr_patch:.2f}")
print(f"Test full-frame PSNR: {test_psnr_full:.2f}")

@torch.no_grad()
def evaluate_bicubic_full_frame(loader, scale=4):
    psnrs = []

    for lr_seq, hr_seq, clip_name, start_idx in loader:
        lr_mid = lr_seq[:, lr_seq.shape[1] // 2]   # [1, C, H, W]
        hr_mid = hr_seq[:, hr_seq.shape[1] // 2]   # [1, C, H, W]

        bicubic = F.interpolate(
            lr_mid,
            scale_factor=scale,
            mode="bicubic",
            align_corners=False
        )

        h = min(bicubic.shape[-2], hr_mid.shape[-2])
        w = min(bicubic.shape[-1], hr_mid.shape[-1])

        bicubic = bicubic[..., :h, :w]
        hr_mid = hr_mid[..., :h, :w]

        psnrs.append(psnr_torch(bicubic, hr_mid))

    return float(np.mean(psnrs)) if len(psnrs) > 0 else 0.0

bicubic_test_psnr = evaluate_bicubic_full_frame(test_full_loader, scale=SCALE)
print(f"Bicubic full-frame PSNR: {bicubic_test_psnr:.2f}")
print(f"Model full-frame PSNR:   {test_psnr_full:.2f}")
print(f"Gain over bicubic:       {test_psnr_full - bicubic_test_psnr:.2f} dB")

def make_demo_lr_frame(frame_bgr, scale=4):
    h, w = frame_bgr.shape[:2]

    small = cv2.resize(
        frame_bgr,
        (w // scale, h // scale),
        interpolation=cv2.INTER_CUBIC
    )

    return small

from collections import deque
import os
import cv2
import numpy as np
import torch

def run_video_vsr(input_video_path, output_video_path, model, device, seq_len=5, scale=4, simulate_lq=True, max_frames=None):
    input_video_path = str(input_video_path)
    output_video_path = str(output_video_path)

    os.makedirs(os.path.dirname(output_video_path), exist_ok=True)

    cap = cv2.VideoCapture(input_video_path)
    if not cap.isOpened():
        raise FileNotFoundError(f"Could not open video: {input_video_path}")

    fps = cap.get(cv2.CAP_PROP_FPS)
    if fps <= 0:
        fps = 25

    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    if simulate_lq:
        out_width, out_height = width, height
    else:
        out_width, out_height = width * scale, height * scale

    fourcc = cv2.VideoWriter_fourcc(*"mp4v")
    out = cv2.VideoWriter(output_video_path, fourcc, fps, (out_width, out_height))

    if not out.isOpened():
        cap.release()
        raise RuntimeError(f"VideoWriter failed to open: {output_video_path}")

    def frame_to_tensor(frame_bgr):
        if simulate_lq:
            frame_bgr = make_demo_lr_frame(frame_bgr, scale=scale)
        frame_rgb = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2RGB)
        tensor = torch.from_numpy(frame_rgb.transpose(2, 0, 1)).float() / 255.0
        return tensor

    print("Preparing streaming inference...")

    ret, first_frame = cap.read()
    if not ret:
        cap.release()
        out.release()
        raise RuntimeError("No frames were read from the input video.")

    first_tensor = frame_to_tensor(first_frame)
    window = deque([first_tensor.clone() for _ in range(seq_len)], maxlen=seq_len)

    processed_count = 0
    frame_count_limit = total_frames if max_frames is None else min(max_frames, total_frames)

    model.eval()
    with torch.no_grad():
        while True:
            input_tensor = torch.stack(list(window), dim=0).unsqueeze(0).to(device)
            output_tensor = model(input_tensor)

            output_img = output_tensor.squeeze(0).cpu().numpy().transpose(1, 2, 0)
            output_img = (np.clip(output_img, 0, 1) * 255).astype(np.uint8)
            output_bgr = cv2.cvtColor(output_img, cv2.COLOR_RGB2BGR)

            if output_bgr.shape[1] != out_width or output_bgr.shape[0] != out_height:
                output_bgr = cv2.resize(output_bgr, (out_width, out_height), interpolation=cv2.INTER_CUBIC)

            out.write(output_bgr)

            processed_count += 1
            if processed_count % 25 == 0:
                print(f"Processed {processed_count}/{frame_count_limit if frame_count_limit > 0 else '?'} frames")

            if max_frames is not None and processed_count >= max_frames:
                break

            ret, next_frame = cap.read()
            if not ret:
                break

            next_tensor = frame_to_tensor(next_frame)
            window.append(next_tensor)

    cap.release()
    out.release()

    if not os.path.exists(output_video_path):
        raise RuntimeError("Output video was not created.")

    file_size = os.path.getsize(output_video_path)
    print(f"Video processing complete. Saved to: {output_video_path}")
    print(f"Output file size: {file_size} bytes")

    if file_size == 0:
        raise RuntimeError("Output video file is empty.")

model.load_state_dict(torch.load(BEST_PATH, map_location=device))
model.to(device)
model.eval()

INPUT_VIDEO = RAW_VIDEO_DIR / "dream.mp4"
OUTPUT_VIDEO = RESULTS_DIR / "vsr_result.mp4"

run_video_vsr(
    INPUT_VIDEO,
    OUTPUT_VIDEO,
    model,
    device,
    seq_len=SEQ_LEN,
    scale=SCALE,
    simulate_lq=True,
    max_frames=300
)

print("OUTPUT_VIDEO =", OUTPUT_VIDEO)
print("exists:", os.path.exists(OUTPUT_VIDEO))
if os.path.exists(OUTPUT_VIDEO):
    print("size:", os.path.getsize(OUTPUT_VIDEO), "bytes")