name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ssh.itay-aknin.com
          username: deploy
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            ~/deploy-upscale-ai.sh
